application: shotofjaqybot
version: 0-0-1e
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: shotofjaqy.py
- url: /assets
  static_dir: assets
- url: /update
  script: updateRSS.py
